SHOW USER;

/* ***** ADMIN ***** */

-- CREACION USUARIOS

CREATE USER PRY2205_EFT
IDENTIFIED BY OracleCloud123
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 250M ON DATA;

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY OracleCloud123
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 250M ON DATA;

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY OracleCloud123
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 250M ON DATA;


-- 1) Privilegios de sistema

-- PRY2205_EFT: crear objetos y sinónimos (públicos/privados)
GRANT CREATE TABLE, CREATE ANY INDEX, CREATE VIEW, CREATE SEQUENCE,
       CREATE SYNONYM, CREATE PUBLIC SYNONYM,CREATE SESSION
TO PRY2205_EFT;

-- PRY2205_EFT_DES: crear vista, perfil, usuarios
GRANT CREATE VIEW, CREATE PROFILE, CREATE USER,CREATE SESSION
TO PRY2205_EFT_DES;

-- PRY2205_EFT_CON: solo ejecución de consultas mediante sinónimos públicos
GRANT CREATE SESSION, CREATE SYNONYM TO PRY2205_EFT_CON;

-------------------------------
-- 2) Roles para acceso a datos
-------------------------------
CREATE ROLE PRY2205_DES_ROL;
CREATE ROLE PRY2205_CON_ROL;

-- Asignar roles
GRANT PRY2205_DES_ROL TO PRY2205_EFT_DES;
GRANT PRY2205_CON_ROL TO PRY2205_EFT_CON;

-------------------------------
-- 3) Public synonyms sobre objetos del owner (PRY2205_EFT)
-------------------------------
CREATE OR REPLACE PUBLIC SYNONYM SYN_AFP        FOR PRY2205_EFT.AFP;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ISAPRE     FOR PRY2205_EFT.ISAPRE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROFESION  FOR PRY2205_EFT.PROFESION;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPRESA    FOR PRY2205_EFT.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_COMUNA     FOR PRY2205_EFT.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_SECTOR     FOR PRY2205_EFT.SECTOR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_TCONTRATO  FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ASESORIA   FOR PRY2205_EFT.ASESORIA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_RANGOS     FOR PRY2205_EFT.RANGOS_SUELDOS;

CREATE OR REPLACE PUBLIC SYNONYM SYN_CARTOLA_PROF FOR PRY2205_EFT_DES.CARTOLA_PROFESIONALES;

-------------------------------
-- 4) Concesión de datos vía roles
-------------------------------
-- Accesos para desarrollador
GRANT SELECT ON PRY2205_EFT.AFP           TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.ISAPRE        TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.PROFESION     TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.PROFESIONAL   TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.EMPRESA       TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.COMUNA        TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.SECTOR        TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.ASESORIA      TO PRY2205_DES_ROL;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_DES_ROL;

-- Accesos para consulta
GRANT SELECT ON PRY2205_EFT.AFP           TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.ISAPRE        TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.PROFESION     TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.PROFESIONAL   TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.EMPRESA       TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_CON_ROL;
GRANT SELECT ON PRY2205_EFT.ASESORIA      TO PRY2205_CON_ROL;

-- Acceso del usuario de consulta a la tabla del informe en DES
GRANT SELECT ON PRY2205_EFT_DES.CARTOLA_PROFESIONALES TO PRY2205_CON_ROL;





/* ***** USUARIO PRY2205_EFT ***** */

SHOW USER;

-- EJECUCION DE SCRIPT DDL CON DML

-- Vista editable VW_EMPRESAS_ASESORADAS

CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  TO_CHAR(e.RUT_EMPRESA, '99G999G999') || '-' || DV_EMPRESA    AS RUT_EMPRESA,
  UPPER(e.NOMEMPRESA)                           AS NOMBRE_EMPRESA,
  e.IVA_DECLARADO                               AS IVA,
  TRUNC(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES) / 12) AS ANIOS_EXISTENCIA,
  -- Promedio anual: total asesorías del año / 12
  ROUND( ( SELECT COUNT(*) 
           FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) / 12
       )                                         AS TOTAL_ASESORIAS_ANUALES,
  -- Devolución IVA estimada: IVA * promedio anual / 100
  ROUND( e.IVA_DECLARADO * 
         ( ( SELECT COUNT(*) 
             FROM SYN_ASESORIA a
             WHERE a.IDEMPRESA = e.IDEMPRESA
               AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) / 12
           ) / 100
       )                                         AS DEVOLUCION_IVA,
  CASE
    WHEN ( SELECT COUNT(*) 
           FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) / 12 > 5
      THEN 'CLIENTE PREMIUM'
    WHEN ( SELECT COUNT(*) 
           FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) / 12 BETWEEN 3 AND 5
      THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END                                           AS TIPO_CLIENTE,
  CASE
    WHEN ( SELECT COUNT(*) FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) >= 7
      THEN '1 ASESORIA GRATIS'
    WHEN ( SELECT COUNT(*) FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) < 7
      AND ( SELECT COUNT(*) FROM SYN_ASESORIA a
             WHERE a.IDEMPRESA = e.IDEMPRESA
               AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) / 12 > 5
      THEN '1 ASESORIA 40% DE DESCUENTO'
    WHEN ( SELECT COUNT(*) FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) = 5
      THEN '1 ASESORIA 30% DE DESCUENTO'
    WHEN ( SELECT COUNT(*) FROM SYN_ASESORIA a
           WHERE a.IDEMPRESA = e.IDEMPRESA
             AND EXTRACT(YEAR FROM a.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1 ) < 5
      THEN '1 ASESORIA 20% DE DESCUENTO'
    ELSE 'CAPTAR CLIENTE'
  END                                           AS CORRESPONDE
FROM SYN_EMPRESA e
ORDER BY e.NOMEMPRESA ASC;

-- Dar permiso de consulta al usuario de informes
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;




/* ***** USUARIO PRY2205_EFT_DES ***** */
-- Conectado como PRY2205_EFT_DES
SHOW USER;

--activacion de rol
SET ROLE PRY2205_DES_ROL;

-------------------------------
-- 1) Tabla para almacenar el informe (Caso 2)
-------------------------------
CREATE TABLE CARTOLA_PROFESIONALES (
  RUT_PROFESIONAL           VARCHAR2(10),
  NOMBRE_PROFESIONAL        VARCHAR2(50),
  PROFESION                 VARCHAR2(25),
  ISAPRE                    VARCHAR2(25),
  SUELDO_BASE               NUMBER(8),
  PORC_COMISION_PROFESIONAL NUMBER(3,2),
  VALOR_TOTAL_COMISION      NUMBER(8),
  PORCENTATE_HONORARIO      NUMBER(8),
  BONO_MOVILIZACION         NUMBER(8),
  TOTAL_PAGAR               NUMBER(8)
);

-------------------------------
-- 2) Poblar con SELECT usando sinónimos públicos
-- Orden: profesión, sueldo desc, porcentaje de comisión, rut
-------------------------------
INSERT INTO CARTOLA_PROFESIONALES (
  RUT_PROFESIONAL, NOMBRE_PROFESIONAL, PROFESION, ISAPRE,
  SUELDO_BASE, PORC_COMISION_PROFESIONAL, VALOR_TOTAL_COMISION,
  PORCENTATE_HONORARIO, BONO_MOVILIZACION, TOTAL_PAGAR
)
SELECT
  p.RUTPROF AS RUT_PROFESIONAL,
  INITCAP(p.APPPRO || ' ' || p.APMPRO || ' ' || p.NOMPRO) AS NOMBRE_PROFESIONAL,
  INITCAP(pr.NOMPROFESION) AS PROFESION,
  INITCAP(i.NOMISAPRE) AS ISAPRE,
  p.SUELDO AS SUELDO_BASE,
  NVL(p.COMISION, 0) AS PORC_COMISION_PROFESIONAL,
  ROUND(NVL(p.COMISION, 0) * p.SUELDO) AS VALOR_TOTAL_COMISION,
  -- HONOR_PCT según rangos
  ROUND(
    ( SELECT r.HONOR_PCT
      FROM SYN_RANGOS r
      WHERE p.SUELDO BETWEEN r.S_MIN AND r.S_MAX
    ) * p.SUELDO / 100
  ) AS PORCENTATE_HONORARIO,
  -- Bono por tipo contrato
  CASE INITCAP(tc.NOMTCONTRATO)
    WHEN 'INDEFINIDO JORNADA COMPLETA' THEN 150000
    WHEN 'INDEFINIDO JORNADA PARCIAL'  THEN 120000
    WHEN 'PLAZO FIJO'                  THEN  60000
    WHEN 'HONORARIOS'                  THEN  50000
    ELSE 0
  END AS BONO_MOVILIZACION,
  -- Total a pagar
  ROUND(
    p.SUELDO
    + ROUND(NVL(p.COMISION, 0) * p.SUELDO)
    + ROUND(
        ( SELECT r.HONOR_PCT
          FROM SYN_RANGOS r
          WHERE p.SUELDO BETWEEN r.S_MIN AND r.S_MAX
        ) * p.SUELDO / 100
      )
    + CASE INITCAP(tc.NOMTCONTRATO)
        WHEN 'INDEFINIDO JORNADA COMPLETA' THEN 150000
        WHEN 'INDEFINIDO JORNADA PARCIAL'  THEN 120000
        WHEN 'PLAZO FIJO'                  THEN  60000
        WHEN 'HONORARIOS'                  THEN  50000
        ELSE 0
      END
  ) AS TOTAL_PAGAR
FROM SYN_PROFESIONAL p
JOIN SYN_PROFESION  pr ON pr.IDPROFESION = p.IDPROFESION
JOIN SYN_ISAPRE     i  ON i.IDISAPRE     = p.IDISAPRE
JOIN SYN_TCONTRATO  tc ON tc.IDTCONTRATO = p.IDTCONTRATO
ORDER BY
  INITCAP(pr.NOMPROFESION),
  p.SUELDO DESC,
  NVL(p.COMISION, 0),
  p.RUTPROF;

COMMIT;

-- 3) Conceder acceso al usuario de consulta

GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;

SET ROLE PRY2205_DES_ROL;




/* ***** USUARIO PRY2205_EFT_CON ***** */
-- Conectado como PRY2205_EFT_CON
SHOW USER;

-- consulta del informe usando el sinónimo público
SELECT *
FROM SYN_CARTOLA_PROF
ORDER BY PROFESION, SUELDO_BASE DESC, PORC_COMISION_PROFESIONAL, RUT_PROFESIONAL;

-- consulta de la vista de empresas asesoradas
SELECT *
FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA;



