
--Informe control stock libros:

-- Crear secuencia para correlativo
CREATE SEQUENCE SEQ_CONTROL_STOCK START WITH 1 INCREMENT BY 1;

-- Crear tabla
CREATE TABLE CONTROL_STOCK_LIBROS_TMP AS

SELECT
  L.LIBROID                 AS ID_LIBRO,
  L.NOMBRE_LIBRO,
  COUNT(E.EJEMPLARID)       AS TOTAL_EJEMPLARES,
  SUM(CASE WHEN P.FECHA_TERMINO IS NULL THEN 1 ELSE 0 END) AS EN_PRESTAMO,
  COUNT(E.EJEMPLARID) - SUM(CASE WHEN P.FECHA_TERMINO IS NULL THEN 1 ELSE 0 END) AS DISPONIBLES,
  ROUND((SUM(CASE WHEN P.FECHA_TERMINO IS NULL THEN 1 ELSE 0 END) / COUNT(E.EJEMPLARID)) * 100) AS PORCENTAJE_PRESTAMO,
  CASE WHEN (COUNT(E.EJEMPLARID) - SUM(CASE WHEN P.FECHA_TERMINO IS NULL THEN 1 ELSE 0 END)) > 2
       THEN 'S' ELSE 'N' END AS STOCK_CRITICO
FROM LIB L
JOIN EJEMPLAR E ON L.LIBROID = E.LIBROID
LEFT JOIN PRE P ON E.EJEMPLARID = P.EJEMPLARID
               AND E.LIBROID    = P.LIBROID
WHERE EXTRACT(YEAR FROM P.FECHA_INICIO) = EXTRACT(YEAR FROM SYSDATE) - 2
  AND P.EMPLEADOID IN (190,180,150)
GROUP BY L.LIBROID, L.NOMBRE_LIBRO
ORDER BY L.LIBROID;




--Vista detalle multas:

CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS

SELECT P.PRESTAMOID AS ID_PRESTAMO,
       A.NOMBRE || ' ' || A.APATERNO AS NOMBRE_ALUMNO,
       C.DESCRIPCION AS NOMBRE_CARRERA,
       L.LIBROID AS ID_LIBRO,
       L.PRECIO AS VALOR_LIBRO,
       P.FECHA_TERMINO,
       P.FECHA_ENTREGA,
       (P.FECHA_ENTREGA - P.FECHA_TERMINO) AS DIAS_ATRASO,
       ROUND(L.PRECIO * 0.03 * (P.FECHA_ENTREGA - P.FECHA_TERMINO)) AS VALOR_MULTA,
       NVL(R.PORC_REBAJA_MULTA,0) AS PORCENTAJE_REBAJA_MULTA,
       ROUND((L.PRECIO * 0.03 * (P.FECHA_ENTREGA - P.FECHA_TERMINO)) * (1 - NVL(R.PORC_REBAJA_MULTA,0)/100)) AS VALOR_REBAJADO
FROM PRE P
JOIN ALU A ON P.ALUMNOID = A.ALUMNOID
JOIN CAR C ON A.CARRERAID = C.CARRERAID
JOIN LIB L ON P.LIBROID = L.LIBROID
LEFT JOIN REBAJA_MULTA R ON C.CARRERAID = R.CARRERAID
WHERE EXTRACT(YEAR FROM P.FECHA_TERMINO) = EXTRACT(YEAR FROM SYSDATE) - 2
  AND P.FECHA_ENTREGA > P.FECHA_TERMINO
ORDER BY P.FECHA_ENTREGA DESC;


